### ISSUE TITLE
Variant representation

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-format#10]
We should discuss how to best represent variants. Probably we need something flexible like
<variant>
<type>HGVS</type>
<content>NM_123:c.-123C>T</content>
<variant>
with various types that also work for chromosomes, microdeletions, and other sets of findings that might be protein biomarkers etc, so that this standard can be used with a wide range of diseases and publications.

**Comment by cmungall** [comment]
Apologies, the commit above appears to be unrelated

This is what we have as an example:

```
schema: phenopacket-level-1
comment: This is an example phenopacket containing one variant to phenotype association
ontologies:
  - id: hp
    version: "2016-02-01"
variants:
  - id: _:v1
    positions:
      - type: HGVS
        value: "NM_123:c.-123C>T"
phenotype_profile:
  - entity: _:v1
    evidence:
      type: TAS
      source:
        id: PMID:FAKE1234
        title: Mutations in NM_123 cause multisystem proteinopathy and ALS
    phenotype:
      type:
        id: HP:0003560
        label: Muscular dystrophy
      onset:
        type:
          id: HP:0003584
          label: Late onset
      description: blah blah
    created: 2016-01-14
    contributors:
      - id: ORCID:nnnn-nnnn-nnnn
```

on the one hand this is scope creep. On the other hand this is practically v useful. The approach is to be modular. The variant part is separable, can be represented outside and referenced, or can be embedded in. Same approach for ped.
