### ISSUE TITLE
negation

### ISSUE THREAD

**Issue by harryhoch** [phenopackets/phenopacket-format#20]
negation not handled in schema:

```
phenotype:
  type:
    not:
      id: HP:0001608
      label: Abnormality of the voice
```

does not validate
