### ISSUE TITLE
Use of evidence codes

### ISSUE THREAD

**Issue by mcourtot** [phenopackets/phenopacket-format#86]
Should the evidence in the example at https://github.com/phenopackets/phenopacket-format/wiki/Tutorial be relying on the ECO codes, such as instead of having 
```
    evidence:
      - types:
          id: TAS
```
this should be
```
   evidence:
      - types:
          id: ECO:0000033
          label: traceable author statement
```
